# Generated by Django 5.1.1 on 2024-09-14 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_invitation_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='role',
        ),
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 8, 44, 15, 929250, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='invitation',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
