# Generated by Django 5.1.1 on 2024-09-16 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_message_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 14, 56, 0, 996979, tzinfo=datetime.timezone.utc)),
        ),
    ]
